### ISSUE TITLE
Rename the Check API Status button id/class

### ISSUE THREAD

**Issue by danielmilner** [firetreedesign/ccbpress-core#4]
Rename the check api status button id/class because it conflicts with the paid version of CCBPress

**Comment by firetreedesign** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename the check api status button id/class because it conflicts with the paid version of CCBPress](https://trello.com/c/7o4FGrRs/44-rename-the-check-api-status-button-id-class-because-it-conflicts-with-the-paid-version-of-ccbpress)

**Comment by danielmilner** [comment]
Resolved with commit 7fde26a
