### ISSUE TITLE
No longer need to check for the default image in event_profile or event_profiles

### ISSUE THREAD

**Issue by danielmilner** [firetreedesign/ccbpress-core#5]
Church Community Builder changed their API so that no image is returned if a custom image has not been uploaded.

**Comment by firetreedesign** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No longer need to check for the default image in event_profile or event_profiles](https://trello.com/c/CNrV3BKi/56-no-longer-need-to-check-for-the-default-image-in-event-profile-or-event-profiles)

**Comment by danielmilner** [comment]
Resolved with commit 7fde26a
